### ISSUE TITLE
JSFromHell and jspm.io

### ISSUE THREAD

**Issue by trusktr** [JSFromHell/JSFromHell#1]
Greetings. I added JSFromHell to the [jspm registry](https://github.com/jspm/registry/pull/48). http://jspm.io

Cheers!

**Comment by jonasraoni** [comment]
ACK! The site is quite abandoned though, maybe when I get retired I'll get
back to my coding hobbie :)

On Fri, Oct 10, 2014 at 1:36 AM, Joseph Orbegoso Pea <
notifications@github.com> wrote:

> Greetings. I added JSFromHell to the jspm registry
> https://github.com/jspm/registry/pull/48. http://jspm.io
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jonasraoni/JSFromHell/issues/1.

## 

Jonas Raoni Soares Silva
http://raoni.org

**Comment by trusktr** [comment]
Definitely do! :)
